[package]
name = "voronoi"
version = "0.1.2"
edition = "2024"

[dependencies]
clap = { version = "4.5.52", features = ["derive"] }
image = "0.25.9"
rand = "0.9.2"

[lints.clippy]
pedantic = "warn"

[profile.release.build-override]
opt-level = 1
